config/routes.rb
Rails.application.routes.draw do
  resources :albums do
    member do
      patch :publish
    end

    resources :tracks
  end
  
  root "albums#index"
end

app/models/album.rb
class Album < ApplicationRecord
	include ImmutableIfPublished

	has_one_attached :cover_image
	has_many :tracks, dependent: :destroy

	enum state: { draft: 0, published: 1 }

  validates :name, presence: true

	def durations
		tracks.sum(:duration)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/immutable_if_published.rb
module ImmutableIfPublished
  extend ActiveSupport::Concern

  included do
    before_update :prevent_changes_if_published
    before_destroy :prevent_deletion_if_published
  end

  private

  def prevent_changes_if_published
    # Disallow updates if already published
    if respond_to?(:state) && state_was == "published" && state != "published"
      errors.add(:base, "Cannot modify a published album.")
      throw(:abort)
    end

    # Allow changes if transitioning to published state
    return if respond_to?(:state) && state_changed? && state == "published"

    # Prevent other modifications if already published
    if respond_to?(:published?) && published?
      errors.add(:base, "Cannot modify a published album.")
      throw(:abort)
    end
  end

  def prevent_deletion_if_published
    if respond_to?(:published?) && published?
      errors.add(:base, "Cannot delete a published album.")
      throw(:abort)
    end
  end
end

app/models/track.rb
class Track < ApplicationRecord
	include ImmutableIfPublished

  belongs_to :album

  validates :title, presence: true
  validates :artist_name, presence: true
  validates :duration, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

	enum state: { draft: 0, published: 1 }

  def published?
    album.published?
  end

  def draft?
    album.draft?
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ edit update destroy publish ]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def edit
    redirect_to albums_path if @album.published?
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      respond_to do |format|
        format.html { redirect_to albums_url, notice: "Album was successfully created." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_album", partial: "albums/form", locals: { album: @album }) }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to albums_url, notice: "Album was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @album.destroy
        format.html { redirect_to albums_path, notice: "Album was successfully destroyed." }
      else
        format.html { redirect_to albums_path, notice: @album.errors.full_messages.to_sentence }
      end
    end
  end

  def publish
    respond_to do |format|
      if @album.draft?
        @album.published!
        format.html { redirect_to albums_path, notice: "Album has been successfully published." }
      else
          format.html { redirect_to albums_path, notice: "Album is already published." }
      end
    end
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:name, :state, :cover_image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_album
  before_action :set_track, only: [:edit, :update, :destroy]

  def new
    @track = @album.tracks.new
  end

  def create
    @track = @album.tracks.new(track_params)
    if @track.save
      respond_to do |format|
        format.html { redirect_to new_album_track_path(@album), notice: "Track was successfully created." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_track", partial: "tracks/form", locals: { track: @track }) }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to edit_album_path(@track.album), notice: "Track was successfully updated." }
      else
        format.html { redirect_to edit_album_path(@track.album), notice: @track.album.errors.full_messages.to_sentence }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @track.destroy
        format.html { redirect_to edit_album_path(@track.album), notice: "Track was successfully destroyed." }
      else
        format.html { redirect_to edit_album_path(@track.album), notice: @track.album.errors.full_messages.to_sentence }
      end
    end
  end

  private

  def set_album
    @album = Album.find(params[:album_id])
  end

  def set_track
    @track = @album.tracks.find(params[:id])
  end

  def track_params
    params.require(:track).permit(:title, :artist_name, :duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def seconds_to_minutes(seconds)
		minutes = seconds / 60
		remaining_seconds = seconds % 60
		"#{minutes}:#{format('%02d', remaining_seconds)}"
	end

	def album_cover_image(album, size: "max-w-32")
    if album.cover_image.attached?
      image_tag(album.cover_image, class: size)
    else
      image_tag("https://placehold.co/400", class: size)
    end
  end
end

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>" class="p-4 border rounded mb-5">
  <div class="flex justify-between items-center mb-5">
    <div class="flex items-center space-x-4">
      <%= album_cover_image(album) %>
      <div class="px-5"> 
        <p class="text-2xl">
          <%= album.name %>
        </p>
        <p>
          <%= seconds_to_minutes(album.durations) %>
        </p>
      </div>
    </div>

    <div class="flex items-center space-x-4">
      <% if album.draft? %>
        <%= button_to "Publish", publish_album_path(album), method: :patch, data: { turbo_confirm: "Are you sure?" }, class: "rounded-lg py-3 px-5 bg-green-700 text-white block font-medium" %>
        <%= link_to "Edit", edit_album_path(album), class: "rounded-lg py-3 px-5 bg-blue-950 text-white block font-medium" %>
        <%= button_to "Delete", album, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "rounded-lg py-3 px-5 bg-rose-950 text-white block font-medium" %>
      <% else %>
        <p>Published</p>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="flex justify-between items-center">
    <ul class="w-full p-4 pt-0">
      <% if album.tracks.any? %>
        <%= render album.tracks %>
      <% else %>
        <li class="my-2">No tracks found</li>
        <hr>
      <% end %>
    </ul>
  </div>
</div>

app/views/albums/_albums.html.erb
<% @albums.each do |album| %>
  <%= render album %>
<% end %>

app/views/albums/_form.html.erb
<div class= "w-full flex items-center justify-between space-x-4">
  <%= form.file_field :cover_image, class: "block w-full" %>
  <%= form.text_field :name, placeholder: "Album Name", class: "block w-full px-4 py-2 border border-gray-300 rounded-md focus:ring focus:ring-blue-200 focus:outline-none" %>
</div>

app/views/albums/create.turbo_stream.erb
<%= turbo_stream.append "albums", partial: "albums/album", locals: { album: @album } %>

app/views/albums/edit.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl p-4">Edit Album</h1>
  <div id="<%= dom_id @album %>" class="p-4 border rounded mb-5 mb-4 w-full">
    <div class="flex items-center mb-5">
      <div class="flex items-center space-x-4 w-full">
        <%= album_cover_image(@album) %>
        <p class="text-2xl px-5">
          <%= form_with model: @album, data: { turbo_frame: "albums" }, class: "flex items-center space-x-4 w-full" do |f| %>
            <%= render "form", album: @album, form: f %>

            <button type="submit" class="flex items-center space-x-1 px-4 py-2 bg-green-700 text-white rounded-md hover:bg-green-600">
              &#x2713;
            </button>
          <% end %>
        </p>
      </div>
    </div>
    <hr>
    <div class="flex justify-between p-4 pt-0 items-center">
      <ul id="tracks" class="w-full pt-0">
        <% if @album.tracks.present? %>
          <%= render @album.tracks %>
        <% else %>
          <li class="my-2">No tracks found</li>
          <hr>
        <% end %>
      </ul>
    </div>

    <div class="p-4 pt-0">
      <%= turbo_frame_tag "new_track" do %>
        <%= link_to "Add New Track", new_album_track_path(@album), class: "rounded-lg w-40 py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
      <% end %>
    </div>
  </div>

  <%= link_to "Cancel", albums_path, "data-turbo-method": "get", class: "rounded-lg w-30 py-3 px-5 bg-rose-950 text-white inline-block font-medium hover:bg-rose-700" %>
</div>

app/views/albums/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-5">
    <h1 class="font-bold text-4xl">Album Catalog</h1>
    <%= turbo_frame_tag "new_album" do %>
      <%= link_to "New Album", new_album_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="albums" class="min-w-full">
    <%= render @albums %>
  </div>
</div>

app/views/albums/new.html.erb
<%= turbo_frame_tag "new_album" do %>
  <%= form_with model: @album, data: { turbo_frame: "albums" }, class: "flex items-center space-x-4 w-full" do |form| %>

    <%= render "form", album: @album, form: form %>

    <button type="submit" class="flex items-center space-x-1 px-4 py-2 bg-green-700 text-white rounded-md hover:bg-green-600">
      &#x2713;
    </button>

    <%= link_to albums_path, "data-turbo-method": "get", class: "flex items-center space-x-1 px-4 py-2 bg-rose-950 text-white rounded-md hover:bg-rose-700" do %>
      &#x2715;
    <% end %>

  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Album Catalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto my-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tracks/_form.html.erb
<%= form_with model: [ @album, @track ], data: { turbo_frame: "tracks" }, class: "w-full flex items-center justify-between" do |f| %>
  <div class="my-4">
    <%= f.text_field :title, placeholder: "Track Title", class: "block py-2 border border-gray-300 rounded-md focus:ring focus:ring-blue-200 focus:outline-none" %>
    <% if @track.errors[:title].any? %>
      <p class="text-red-500 text-sm mt-1"><%= @track.errors[:artist_name].first %></p>
    <% end %>
  </div>
  
  <div class="my-4">
    <%= f.text_field :artist_name, placeholder: "Artist Name", class: "block border border-gray-300 rounded-md focus:ring focus:ring-blue-200 focus:outline-none" %>
    <% if @track.errors[:artist_name].any? %>
      <p class="text-red-500 text-sm mt-1"><%= @track.errors[:artist_name].first %></p>
    <% end %>
  </div>

  <div class="my-4">
    <%= f.number_field :duration, min: 0, step: 1, placeholder: "Duration in minutes", class: "block border border-gray-300 rounded-md focus:ring focus:ring-blue-200 focus:outline-none" %>
  </div>
  
  <div class="flex items-center space-x-4 my-4">
    <button type="submit" class="inline-block space-x-1 px-4 py-2 bg-green-700 text-white rounded-md hover:bg-green-600">
      &#x2713;
    </button>
  </div>
<% end %>
<% if action_name == "edit" %>
  <%= button_to "delete", [ @album, @track ], method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "block space-x-1 px-4 py-2 bg-rose-950 text-white rounded-md hover:bg-rose-700 mb-4" %>
<% end %>

app/views/tracks/_track.html.erb
<li id="<%= dom_id track %>">
  <%= turbo_frame_tag "edit_track" do %>
    <div class="my-4 flex justify-between items-center">
      <div>
        <p class="inline-block" style="min-width: 80px;"><%= track.title %></p>
        <p><%= track.artist_name %></p>
      </div>
      <div><%= seconds_to_minutes(track.duration) %></div>
      <% if action_name == "edit" || action_name == "create" %>
        <%= link_to "Edit", edit_album_track_path(track.album, track), class: "rounded-lg py-3 px-5 bg-blue-950 text-white block font-medium" %>
      <% end %>
    </div>
  <% end %>
  <hr>
</li>

app/views/tracks/_tracks.html.erb
<ul id="tracks" class="w-full pt-0">
  <% @album.tracks.each do |track| %>
    <%= render track %>
  <% end %>
</ul>

app/views/tracks/create.turbo_stream.erb
<%= turbo_stream.append "tracks", partial: "tracks/track", locals: { track: @track } %>

app/views/tracks/edit.html.erb
<%= turbo_frame_tag "edit_track" do %>
  <%= render "form", track: @track %>
<% end %>

app/views/tracks/new.html.erb
<%= turbo_frame_tag "new_track" do %>
  <%= render "form", track: @track %>
<% end %>